config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/stevenjgibbons/LEOPACK-2022-revision:
      branch: main
      repo: https://github.com/stevenjgibbons/LEOPACK-2022-revision
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/stevenjgibbons/LEOPACK-2022-revision git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-heliotrope-dolphin.sh
        container: qc.acc_nerdy-olive-rattlesnake
  QC.Doc:
    repos:
      github.com/stevenjgibbons/LEOPACK-2022-revision find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.beady-viridian-nightingale.sh
        container: qc.doc_tasty-maroon-loon
      github.com/stevenjgibbons/LEOPACK-2022-revision git:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-saffron-indri.sh
        container: qc.doc_scaly-wisteria-uakari
      github.com/stevenjgibbons/LEOPACK-2022-revision markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-lavender-cuttlefish.sh
        container: qc.doc_shaggy-tomato-beetle
  QC.Lic:
    repos:
      github.com/stevenjgibbons/LEOPACK-2022-revision licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-zucchini-boar.sh
        container: qc.lic_cheeky-zucchini-balinese
  QC.Ver:
    repos:
      github.com/stevenjgibbons/LEOPACK-2022-revision get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-sapphire-buffalo.sh
        container: qc.ver_cheeky-taupe-crane
timeout: 5400
