config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/stevenjgibbons/LEOPACK-2022-revision:
      branch: main
      repo: https://github.com/stevenjgibbons/LEOPACK-2022-revision
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/stevenjgibbons/LEOPACK-2022-revision git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-ecru-newfoundland.sh
        container: qc.acc_sleazy-lilac-birman
  QC.Doc:
    repos:
      github.com/stevenjgibbons/LEOPACK-2022-revision find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-flax-sparrow.sh
        container: qc.doc_cloudy-apricot-anteater
      github.com/stevenjgibbons/LEOPACK-2022-revision git:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-gold-toucan.sh
        container: qc.doc_trippy-flax-turtle
      github.com/stevenjgibbons/LEOPACK-2022-revision markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-chestnut-hippopotamus.sh
        container: qc.doc_cranky-amaranth-lobster
  QC.Lic:
    repos:
      github.com/stevenjgibbons/LEOPACK-2022-revision licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-khaki-hornet.sh
        container: qc.lic_sloppy-tomato-quokka
  QC.Met:
    repos:
      github.com/stevenjgibbons/LEOPACK-2022-revision cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-buff-caiman.sh
        container: qc.met_zippy-periwinkle-emu
  QC.Ver:
    repos:
      github.com/stevenjgibbons/LEOPACK-2022-revision get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-azure-flamingo.sh
        container: qc.ver_gimpy-jade-lionfish
timeout: 5400
